# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-05-26 10:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_host_administrator'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='\u9a8c\u8bc1\u7801')),
                ('email', models.EmailField(max_length=50, verbose_name='\u90ae\u7bb1')),
                ('send_type', models.CharField(choices=[(b'register', '\u6ce8\u518c'), (b'forget', '\u627e\u56de\u5bc6\u7801')], max_length=10, verbose_name='\u9a8c\u8bc1\u7801\u7c7b\u578b')),
                ('send_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u53d1\u9001\u65f6\u95f4')),
            ],
        ),
        migrations.CreateModel(
            name='resource_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=20)),
                ('device_name', models.CharField(blank=True, max_length=50)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('device_funcation', models.CharField(blank=True, max_length=100)),
                ('STATUS', models.CharField(blank=True, choices=[('\u4f7f\u7528\u4e2d', '\u4f7f\u7528\u4e2d'), ('\u672a\u4f7f\u7528', '\u672a\u4f7f\u7528')], max_length=10)),
                ('ADDRESS', models.TextField(blank=True, max_length=100)),
                ('IP_INTERNAL', models.CharField(blank=True, max_length=40)),
                ('IP_MDCN', models.CharField(blank=True, max_length=40)),
                ('IP_MANAGE', models.CharField(blank=True, max_length=40)),
                ('POWER', models.CharField(blank=True, max_length=10)),
                ('MEMORY', models.CharField(blank=True, max_length=10)),
                ('CPU', models.CharField(blank=True, max_length=40)),
                ('THREADCOUNT_CPU', models.CharField(blank=True, default=b'24', max_length=10)),
                ('DISK', models.CharField(blank=True, max_length=20)),
                ('DISK_SSD', models.CharField(blank=True, max_length=20)),
                ('RAID', models.CharField(blank=True, max_length=50)),
                ('VENDORNAME', models.CharField(blank=True, max_length=20)),
                ('MODEL', models.CharField(blank=True, max_length=20)),
                ('SN', models.CharField(blank=True, max_length=50)),
                ('HIGH', models.CharField(blank=True, max_length=10)),
                ('starDatetime_warranty', models.DateField(blank=True)),
                ('endDatetime_warranty', models.DateField(blank=True)),
            ],
            options={
                'ordering': ['id'],
                'verbose_name_plural': 'Resource_list',
            },
        ),
        migrations.DeleteModel(
            name='AccessRecord',
        ),
        migrations.RemoveField(
            model_name='host',
            name='administrator',
        ),
        migrations.RemoveField(
            model_name='host',
            name='idc',
        ),
        migrations.RemoveField(
            model_name='hostgroup',
            name='hosts',
        ),
        migrations.RemoveField(
            model_name='idc',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='maintainlog',
            name='host',
        ),
        migrations.DeleteModel(
            name='Host',
        ),
        migrations.DeleteModel(
            name='HostGroup',
        ),
        migrations.DeleteModel(
            name='IDC',
        ),
        migrations.DeleteModel(
            name='MaintainLog',
        ),
    ]
