# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-14 03:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170526_0547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailverifyrecord',
            options={'verbose_name': '\u90ae\u7bb1\u9a8c\u8bc1', 'verbose_name_plural': '\u90ae\u7bb1\u9a8c\u8bc1'},
        ),
        migrations.AlterModelOptions(
            name='resource_list',
            options={'ordering': ['id'], 'verbose_name': '\u8d44\u6e90\u5217\u8868', 'verbose_name_plural': '\u8d44\u6e90\u5217\u8868'},
        ),
    ]
