# -*- coding: utf-8 -*-
# Generated by Django 1.9.13 on 2017-06-14 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170614_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='batch_config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=20)),
                ('device_type', models.CharField(blank=True, max_length=50)),
                ('device_funcation', models.CharField(blank=True, max_length=100)),
                ('ADDRESS', models.TextField(blank=True, max_length=100)),
                ('IP_INTERNAL', models.CharField(blank=True, max_length=40)),
                ('IP_MDCN', models.CharField(blank=True, max_length=40)),
                ('IP_MANAGE', models.CharField(blank=True, max_length=40)),
            ],
            options={
                'verbose_name': '\u6279\u91cf\u914d\u7f6e',
                'db_table': 'batch_config',
                'managed': False,
                'verbose_name_plural': '\u6279\u91cf\u914d\u7f6e',
                'default_permissions': [],
            },
        ),
    ]
